apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samtykke-pdfgen
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/is_alive
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: /internal/is_ready
    port: 8080
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 400m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  accessPolicy:
    inbound:
      rules:
        - application: samtykke-api
